- accoj/static/jquery-3.1.1/jquery.cookie.js
- accoj/templates/base.html
1.jquery.cookie.js上传
2.base页中csrf修复未加引号bug
3.前端index页路由更改
> 1.jquery.cookie.js上传2.base页中csrf修复未加引号bug 3.前端index页路由更改

- accoj/blueprints/accoj.py
- accoj/blueprints/auth.py
- accoj/static/js/ajax/course/coursei.js
- accoj/static/js/base.js
- accoj/templates/course/courseBase.html
- accoj/templates/course/coursei.html
> 1.修复若干常规BUG以及两个fatal BUG

- accoj/blueprints/accoj.py
- accoj/deal_business/__init__.py
- accoj/static/js/ajax/course/coursei.js
> 1.处理业务部分重构，增加接口易用性和拓展性

- accoj/static/css/main.css
- accoj/static/js/main.js
- accoj/templates/base.html
- accoj/templates/course/courseii.html
-1-
第II次课程布局调整。
每个会计要素都有两个金额方向，即正和负。
-2-
取消了footer内的GitHub图标。
> FE-v.1.2.5.6

- accoj/blueprints/accoj.py
- accoj/deal_business/__init__.py
- accoj/static/js/ajax/auth.js
- accoj/static/js/ajax/course/coursei.js
- accoj/static/js/base.js
- accoj/templates/course/courseBase.html
- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
> 1.提供用户提示信息统一接口，具体见base.js/show_message()

- AccojDBStruct.txt
- accoj/blueprints/accoj.py
- accoj/deal_business/__init__.py
- accoj/static/js/ajax/course/coursei.js
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/base.js
- accoj/static/js/main.js
- accoj/templates/base.html
- accoj/templates/course/courseBase.html
- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
- accoj/utils/add_question.py
2.新增访问限制，前一次课程未完成，不可访问其他课程
3.用户信息提示接口新增淡出淡入效果
> 1.第二部分课程完成，请更新数据库

- accoj/blueprints/accoj.py
- accoj/static/js/ajax/auth.js
- accoj/static/js/ajax/course/coursei.js
- accoj/static/js/base.js
- accoj/templates/base.html
- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
> 1.增加确认提交模态框

- accoj/blueprints/accoj.py
- accoj/deal_business/__init__.py
- accoj/static/js/ajax/auth.js
- accoj/static/js/ajax/course/coursei.js
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/base.js
- accoj/templates/base.html
- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
> 1.第二部分课程BUG修复

- accoj/blueprints/accoj.py
- accoj/deal_business/__init__.py
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/ajax/course/courseiii.js
- accoj/static/js/base.js
- accoj/static/js/main.js
- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
- accoj/templates/course/courseiii.html
> 1.第三部分课程完成，可正常使用

- accoj/blueprints/accoj.py
- accoj/static/js/ajax/course/coursei.js
- accoj/templates/course/coursei.html
2.修复创立公司时，若提交失败后第二次再次提交失败红色标注框不会刷新的BUG
> 1.修复创立公司时，股东未填写可以提交成功的BUG

- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
- accoj/templates/course/courseiii.html
> FE-1.2.7.1

- accoj/blueprints/accoj.py
- accoj/templates/course/coursei.html
> 1.修复创立公司时，股东填写了但是提交失败的BUG

- accoj/blueprints/accoj.py
- accoj/static/js/ajax/course/coursei.js
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/ajax/course/courseiii.js
- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
- accoj/templates/course/courseiii.html
> 1.第二、三次课程增加保存功能

- accoj/blueprints/accoj.py
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/ajax/course/courseiii.js
- accoj/static/js/base.js
- accoj/static/js/main.js
- accoj/templates/course/courseiv.html
`db.company.updateMany({}, {"$set": {"schedule_confirm.entry_confirm": [], "schedule_saved.entry_saved": []}})`
2.修复已提交仍能保存的BUG
3.保存和提交按钮增加倒计时
> 1.第四次课程完成，可以正常使用，需drop company或者在mongo终端输入下列语句(登录认证后)

- accoj/blueprints/auth.py
- accoj/emails.py
- accoj/static/jquery-3.1.1/jquery.base64.js
- accoj/static/js/ajax/auth.js
- accoj/static/js/base.js
- accoj/templates/base.html
- settings.py
> 1.增加了找回密码功能

- accoj/static/js/ajax/course/courseiii.js
- accoj/static/js/main.js
- accoj/templates/course/courseiii.html
- accoj/templates/course/coursevi.html
- accoj/templates/course/coursevii.html
-1-
第III次课程页面适配手机优化。
-2-
第VI次课程和第VII次课程长表适配手机优化。
> FE-1.2.7.2

- accoj/blueprints/accoj.py
- accoj/static/js/ajax/course/coursev_2.js
- accoj/static/js/ajax/course/coursevii.js
- accoj/templates/course/coursevii.html
> 1.第七次课程科目余额表部分完成，可正常使用

- AccojDBStruct.txt
- accoj/blueprints/accoj.py
- accoj/static/css/course/coursei.css
- accoj/static/css/course/courseiv.css
- accoj/static/css/course/courseviii.css
- accoj/static/css/main.css
- accoj/static/js/ajax/course/courseiv.js
- accoj/static/js/ajax/course/coursev_2.js
- accoj/static/js/ajax/course/courseviii.js
- accoj/static/js/base.js
- accoj/templates/course/courseiv.html
- accoj/templates/course/coursevii.html
- accoj/templates/course/courseviii.html
2.提高了接口可用性
3.请drop company表或在mongo shell中运行下述命令
```
db.company.updateMany({}, {"$set": {"schedule_confirm.new_balance_sheet_confirm": false, "schedule_confirm.profit_statement_confirm": false}})
db.company.updateMany({}, {"$set": {"schedule_saved.new_balance_sheet_saved": false, "schedule_saved.profit_statement_saved": false}})
```
> 1.第八次课程完成，可正常使用

- AccojDBStruct.txt
- accoj/blueprints/accoj.py
- accoj/static/css/course/coursei.css
- accoj/static/css/course/courseiv.css
- accoj/static/css/course/courseix.css
- accoj/static/css/course/coursev_2.css
- accoj/static/css/course/coursevi.css
- accoj/static/css/course/coursevii.css
- accoj/static/css/course/coursex.css
- accoj/static/css/main.css
- accoj/static/js/ajax/course/courseix.js
- accoj/static/js/ajax/course/courseix_2.js
- accoj/static/js/ajax/course/courseix_4.js
- accoj/static/js/ajax/course/coursex.js
- accoj/static/js/base.js
- accoj/templates/course/courseix.html
- accoj/templates/course/courseix_2.html
- accoj/templates/course/courseix_3.html
- accoj/templates/course/courseix_4.html
- accoj/templates/course/courseviii.html
- accoj/templates/course/coursex.html
3.请drop company集合或在mongo shell中运行下述命令
```
db.company.updateMany({}, {"$set": {"schedule_confirm.trend_analysis_confirm":{"first": false, "second": false}}})
db.company.updateMany({}, {"$set": {"schedule_saved.trend_analysis_saved":{"first": false, "second": false}}})
db.company.updateMany({}, {"$set": {"schedule_confirm.common_ratio_analysis_confirm":{"first": false, "second": false}}})
db.company.updateMany({}, {"$set": {"schedule_saved.common_ratio_analysis_saved":{"first": false, "second": false}}})
db.company.updateMany({}, {"$set": {"schedule_confirm.ratio_analysis_confirm":false}})
db.company.updateMany({}, {"$set": {"schedule_saved.ratio_analysis_confirm_saved":false}})
db.company.updateMany({}, {"$set": {"schedule_confirm.dupont_analysis_confirm":false}})
db.company.updateMany({}, …
```
> 1.第九、十次课程完成，可正常使用

- accoj/templates/index.html
> FE-v.1.3.1

- accoj/blueprints/accoj.py
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/ajax/course/courseiii.js
- accoj/static/js/ajax/course/courseiv.js
- accoj/static/js/ajax/course/coursev.js
- accoj/static/js/ajax/course/coursev_2.js
- accoj/static/js/ajax/course/coursevi.js
- accoj/static/js/ajax/course/coursevii.js
- accoj/static/js/base.js
- accoj/templates/course/courseii.html
- accoj/templates/course/courseiii.html
- accoj/templates/course/courseiv.html
- accoj/templates/course/coursevi.html
- accoj/templates/course/coursevii.html
> 1.js部分充分解耦

- accoj/blueprints/accoj.py
- accoj/static/js/ajax/course/coursei.js
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/ajax/course/courseiii.js
- accoj/static/js/ajax/course/courseiv.js
- accoj/static/js/ajax/course/coursev.js
- accoj/static/js/ajax/course/coursevi.js
- accoj/static/js/base.js
- accoj/templates/course/courseii.html
- accoj/templates/course/courseiii.html
- accoj/templates/course/courseiv.html
- accoj/templates/course/coursevi.html
- accoj/utils/__init__.py
> 1.将请求数据条件为，若未保存过则不会发起请求，大幅减少后台请求次数（目前优化进度仅为第二三四六次课程）

- accoj/blueprints/accoj.py
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/ajax/course/courseiii.js
- accoj/static/js/ajax/course/courseiv.js
- accoj/static/js/ajax/course/coursev.js
- accoj/static/js/ajax/course/coursevi.js
2.修复二三四六课程，提交状态标签一直显示为`已保存`的问题
3.修复会计账簿科目下拉框显示为空问题
> 1.修复会计账户部分删除账户`显示成功后`再次刷新仍存在的问题

- accoj/static/css/base.css
- accoj/static/css/main.css
- accoj/templates/base.html
- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
- accoj/templates/course/courseiii.html
- accoj/templates/course/courseiv.html
- accoj/templates/course/courseix.html
- accoj/templates/course/courseix_2.html
- accoj/templates/course/courseix_3.html
- accoj/templates/course/courseix_4.html
- accoj/templates/course/coursev.html
- accoj/templates/course/coursev_2.html
- accoj/templates/course/coursevi.html
- accoj/templates/course/coursevii.html
- accoj/templates/course/courseviii.html
- accoj/templates/course/coursex.html
> Fe v.1.3.3.x

- accoj/static/css/base.css
- accoj/templates/base.html
- accoj/templates/index.html
-1-
index.html
base.html header/footer规范化重构
> FE v.1.4.1.0

- accoj/blueprints/accoj.py
- accoj/static/css/base.css
- accoj/static/js/ajax/course/coursei.js
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/ajax/course/courseiii.js
- accoj/static/js/ajax/course/courseiv.js
- accoj/static/js/ajax/course/courseix.js
- accoj/static/js/ajax/course/courseix_2.js
- accoj/static/js/ajax/course/courseix_4.js
- accoj/static/js/ajax/course/coursev.js
- accoj/static/js/ajax/course/coursev_2.js
- accoj/static/js/ajax/course/coursevi.js
- accoj/static/js/ajax/course/coursevii.js
- accoj/static/js/ajax/course/courseviii.js
- accoj/static/js/ajax/course/coursex.js
- accoj/static/js/base.js
- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
- accoj/templates/course/courseiii.html
- accoj/templates/course/courseiv.html
- accoj/templates/course/courseix.html
- accoj/templates/course/courseix_2.html
- accoj/templates/course/courseix_4.html
- accoj/templates/course/coursev.html
- accoj/templates/course/coursev_2.html
- accoj/templates/course/coursevi.html
- accoj/templates/course/coursevii.html
- accoj/templates/course/courseviii.html
- accoj/templates/course/coursex.html
2.增加input错误提醒接口
3.增加部分标签的冒泡提示信息
> 1.Js统一事件处理

- accoj/blueprints/accoj.py
- accoj/deal_business/__init__.py
- accoj/deal_business/create_questions.py
- accoj/static/css/main.css
- accoj/static/js/ajax/course/coursei.js
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/ajax/course/courseiii.js
- accoj/static/js/ajax/course/courseiv.js
- accoj/static/js/ajax/course/coursevi.js
- accoj/static/js/base.js
- accoj/templates/course/courseiii.html
- accoj/utils/__init__.py
2.请drop file,company,question集合
3.修复注册公司和创建业务无法提交的BUG
4.将`subjects_infos`统一修正改为`subject_infos`
> 1.会计要素和科目部分加入`查看答案`功能，其中会计要素部分已实现`标出错误`功能

- accoj/blueprints/__init__.py
- accoj/blueprints/accoj.py
- accoj/deal_business/__init__.py
- accoj/evaluation/evaluate_acc_document.py
- accoj/static/css/main.css
- accoj/static/js/ajax/course/courseii.js
- accoj/static/js/ajax/course/courseiii.js
- accoj/static/js/ajax/course/courseiv.js
- accoj/static/js/ajax/course/coursevi.js
- accoj/static/js/base.js
- accoj/templates/course/courseii.html
- accoj/templates/course/courseiii.html
- accoj/templates/course/courseiv.html
- accoj/templates/course/coursevi.html
3.分页标签，去掉`href=#`，改用样式`cursor: pointer;`。
> 1.会计凭证部分查看答案完成。

- accoj/static/css/base.css
- accoj/static/css/main.css
- accoj/static/js/ajax/course/coursev.js
- accoj/templates/about.html
- accoj/templates/base.html
- accoj/templates/course/coursei.html
- accoj/templates/course/courseii.html
- accoj/templates/course/courseiii.html
- accoj/templates/course/courseiv.html
- accoj/templates/course/courseix.html
- accoj/templates/course/courseix_2.html
- accoj/templates/course/courseix_4.html
- accoj/templates/course/coursev.html
- accoj/templates/course/coursev_2.html
- accoj/templates/course/coursevi.html
- accoj/templates/course/coursevii.html
- accoj/templates/course/courseviii.html
- accoj/templates/course/coursex.html
FE v.1.4.2 - v.1.4.4
[优化]增强对移动端的技术支持。
[优化]修复部分BUG和调整部分布局。
[优化]对第V次课程的有关HTML的JS代码做了HTML和CSS分离。
> Fe v.1.4.2

- accoj/blueprints/__init__.py
- accoj/blueprints/accoj.py
- accoj/blueprints/admin.py
- accoj/templates/profile/index.html
- accoj/templates/profile/message_system.html
- accoj/templates/profile/message_whisper.html
- accoj/templates/profile/rank.html
- accoj/templates/teacher/index.html
- accoj/templates/teacher/manage-time.html
- accoj/templates/teacher/message_system.html
- accoj/templates/teacher/message_whisper.html
- accoj/templates/teacher/rank.html
- accoj/templates/teacher/teacher-correct.html
- accoj/templates/teacher/teacher-notify-c.html
- accoj/templates/teacher/teacher-notify-p.html
> 1.数据库后台增加Forbidden。

- accoj/blueprints/accoj.py
- accoj/static/js/base.js
- accoj/templates/base.html
> 1.注册公司BUG修复。

- accoj/blueprints/__init__.py
- accoj/blueprints/accoj.py
- accoj/blueprints/api.py
- accoj/blueprints/auth.py
- accoj/static/js/ajax/index.js
- accoj/static/js/ajax/teacher/teacher-notify-p.js
- accoj/templates/errors/403.html
- accoj/templates/errors/404.html
- accoj/templates/errors/500.html
- accoj/templates/index.html
- accoj/templates/profile/profile-base.html
- accoj/templates/profile/profile-schedule.html
- accoj/templates/profile/profile-score.html
- accoj/templates/profile/rank.html
- accoj/templates/teacher/rank.html
- accoj/templates/teacher/teacher-base.html
- accoj/templates/teacher/teacher-correct.html
- accoj/templates/teacher/teacher-notify-c.html
- accoj/templates/teacher/teacher-notify-p.html
> 首页新闻后端已完成，前端接口定义，前端待实现。cnd更换。

- accoj/static/css/base.css
- accoj/static/js/ajax/index.js
- accoj/templates/index.html
> FE-v.1.5.1

- accoj/__init__.py
- accoj/news_spider.py
- settings.py
Reverts HNIT-ACCOJ/hnit-accoj#151
> Revert "new_spider问题部分解决."

- README.md
- accoj/__init__.py
- accoj/blueprints/admin.py
- accoj/blueprints/api.py
- accoj/celery.py
- accoj/news_spider.py
- accoj/utils/__init__.py
- celery_worker.py
- redisDBStruct.md
- settings.py
> 1.将数据库后台root url由'/admin'改为'dbadmin'，请参照更新后的README。

- doc/ACCOJ配置.html
- doc/AccojMongoDBStruct.html
Reverts HNIT-ACCOJ/hnit-accoj#210
> Revert "doc add highlight."

- accoj/blueprints/__init__.py
Reverts HNIT-ACCOJ/hnit-accoj#215
> Revert "bug修复：修复第五部分只有一半分."
